package HrCenterApp;


/**
* HrCenterApp/DEMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Friday, October 26, 2018 5:27:31 o'clock PM EDT
*/

public interface DEMS extends DEMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMS
