package HrCenterApp.DEMSPackage;


/**
* HrCenterApp/DEMSPackage/LocationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Friday, October 26, 2018 5:27:31 o'clock PM EDT
*/

abstract public class LocationHelper
{
  private static String  _id = "IDL:HrCenterApp/DEMS/Location:1.0";

  public static void insert (org.omg.CORBA.Any a, HrCenterApp.DEMSPackage.Location that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HrCenterApp.DEMSPackage.Location extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "locationName",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (HrCenterApp.DEMSPackage.LocationHelper.id (), "Location", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HrCenterApp.DEMSPackage.Location read (org.omg.CORBA.portable.InputStream istream)
  {
    HrCenterApp.DEMSPackage.Location value = new HrCenterApp.DEMSPackage.Location ();
    value.locationName = istream.read_wstring ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HrCenterApp.DEMSPackage.Location value)
  {
    ostream.write_wstring (value.locationName);
  }

}
