package HrCenterApp.DEMSPackage;


/**
* HrCenterApp/DEMSPackage/Location.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Friday, October 26, 2018 5:27:31 o'clock PM EDT
*/

public final class Location implements org.omg.CORBA.portable.IDLEntity
{
  public String locationName = null;

  public Location ()
  {
  } // ctor

  public Location (String _locationName)
  {
    locationName = _locationName;
  } // ctor

} // class Location
