package HrCenterApp.DEMSPackage;


/**
* HrCenterApp/DEMSPackage/ServerLocation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Wednesday, October 24, 2018 6:30:43 o'clock PM EDT
*/

public class ServerLocation implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static HrCenterApp.DEMSPackage.ServerLocation[] __array = new HrCenterApp.DEMSPackage.ServerLocation [__size];

  public static final int _CA = 0;
  public static final HrCenterApp.DEMSPackage.ServerLocation CA = new HrCenterApp.DEMSPackage.ServerLocation(_CA);
  public static final int _US = 1;
  public static final HrCenterApp.DEMSPackage.ServerLocation US = new HrCenterApp.DEMSPackage.ServerLocation(_US);
  public static final int _UK = 2;
  public static final HrCenterApp.DEMSPackage.ServerLocation UK = new HrCenterApp.DEMSPackage.ServerLocation(_UK);

  public int value ()
  {
    return __value;
  }

  public static HrCenterApp.DEMSPackage.ServerLocation from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ServerLocation (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ServerLocation
