package Interface.Corba;


/**
* Interface/Corba/IFrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, November 21, 2018 10:47:27 o'clock PM EST
*/

public interface IFrontEndOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, int employeeID, String mailID, Interface.Corba.Project project, String location);
  String createERecord (String managerID, String firstName, String lastName, int employeeID, String mailID, String projectID);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String location);
  void softwareFailure (String managerID);
  void replicaCrash (String managerID);
} // interface IFrontEndOperations
