package Interface.Corba;

/**
* Interface/Corba/IFrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, November 21, 2018 10:47:27 o'clock PM EST
*/

public final class IFrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public Interface.Corba.IFrontEnd value = null;

  public IFrontEndHolder ()
  {
  }

  public IFrontEndHolder (Interface.Corba.IFrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Interface.Corba.IFrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Interface.Corba.IFrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Interface.Corba.IFrontEndHelper.type ();
  }

}
