package Interface.Corba;


/**
* Interface/Corba/IFrontEndHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, November 21, 2018 10:47:27 o'clock PM EST
*/

abstract public class IFrontEndHelper
{
  private static String  _id = "IDL:Corba/IFrontEnd:1.0";

  public static void insert (org.omg.CORBA.Any a, Interface.Corba.IFrontEnd that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Interface.Corba.IFrontEnd extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Interface.Corba.IFrontEndHelper.id (), "IFrontEnd");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Interface.Corba.IFrontEnd read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IFrontEndStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Interface.Corba.IFrontEnd value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Interface.Corba.IFrontEnd narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Interface.Corba.IFrontEnd)
      return (Interface.Corba.IFrontEnd)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Interface.Corba._IFrontEndStub stub = new Interface.Corba._IFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Interface.Corba.IFrontEnd unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Interface.Corba.IFrontEnd)
      return (Interface.Corba.IFrontEnd)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Interface.Corba._IFrontEndStub stub = new Interface.Corba._IFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
