package Interface.Corba;

/**
* Interface/Corba/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, November 21, 2018 10:47:27 o'clock PM EST
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public Interface.Corba.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (Interface.Corba.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Interface.Corba.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Interface.Corba.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Interface.Corba.ProjectHelper.type ();
  }

}
